### PR TITLE
[*] delete _type in constructor

### PR DESCRIPTION
**Pull request by pariciadra**
Doing CI CD job

### CODE REVIEW

**Comment by pariciadra** [comment]
@Cavonstavant  Your local changes don't effect. Please repush the correct version of my work

**Comment by Cavonstavant** [comment]
> @Cavonstavant  Your local changes don't appear, did you pushed ? Please repush the correct version of my work 

oops

**Comment by Cavonstavant** [comment]
@pariciadra It appears that i did not push :pinata:

**Comment by pariciadra** [comment]
> @pariciadra It appears that i did not push 🪅

Thanks mate

**Pull request merged**
